experimental_monorepo_root = true

[env]
'_'.file = { path = ".env" }
'_'.source = { path = "./git-current.sh" }
DOCKER_BUILDKIT = 1
RP_AUTH_TOKEN = ""
MONOREPO_ROOT = "{{config_root}}"
[monorepo]
config_roots = ["packages/*", "scripts/*"]

[settings]
experimental = true
auto_install = true

[tools]
python = "3.12"
uv = "0.10.7"
hk = "1.36.0"
ruff = "latest"
pkl = "latest"
taplo = "latest"
yamlfmt = "latest"
pinact = "latest"
zizmor = "latest"
github-cli = "latest"
hadolint = "latest"
watchexec = "latest"
"npm:@quobix/vacuum" = "latest"
"npm:@biomejs/biome" = "latest"
"npm:dclint" = "latest"
"trufflehog" = "latest"

[tasks.pre-commit]
run = "hk pre-commit -a"

[tasks.format]
run = "hk fix -a"

[tasks.lint]
run = "hk check -a"

[prepare.uv]
run = "uv sync --all-packages"

[tasks.all-ci]
description = "Will simulate CI environment by running all checks and tests"
run = [
  { task = "//...:generate-libs*" },
  { task = "//:format" },
  { tasks = [
    "//:lint",
    "//...:build",
    "//...:test",
  ] },
]


[tasks.test]
run = "echo no tests defined"

[tasks.registry-login]
description = "Log in to Docker registry"
env = { REGISTRY_PASSWORD = { required = true }, REGISTRY_URL = { required = true }, REGISTRY_USERNAME = { required = true } }
run = 'echo "${REGISTRY_PASSWORD}" | docker login "${REGISTRY_URL}" -u "${REGISTRY_USERNAME}" --password-stdin'

[task_templates.scan-docker]
description = "Scan Docker image for leaked secrets with TruffleHog"
run = """
trufflehog docker --image docker://$IMAGE_NAME --results=verified --fail --json > scan-results.json
"""

[task_templates.push]
description = "Push Docker image to registry"
usage = 'arg "<tag>" var=#true var_min=1 help="Image tags to push"'
run = """
FULL_IMAGE="${REGISTRY_URL}/${REGISTRY_USERNAME}/${IMAGE_NAME}"
for tag in ${usage_tag}; do
  docker tag "${IMAGE_NAME}" "${FULL_IMAGE}:${tag}"
  docker push "${FULL_IMAGE}:${tag}"
done
"""
depends = ["//:registry-login"]

[task_templates.build]
env = { '_'.source = { path = "./github-token.env.sh" } }
run = "docker buildx build --secret id=GITHUB_TOKEN,env=GITHUB_TOKEN -f Dockerfile -t $IMAGE_NAME ../.."
description = "Build the CLI Docker image"

[task_templates.build-push-local]
env = { '_'.source = { path = "./git-diff-hash.sh" } }
description = "Build and auto push Docker image to registry with current git branch and hash along local changes"
usage = 'arg "[tag]" var=#true help="Image tags to push"'
run = [
  { task = "build" },
  { task = "scan-docker" },
  'mise run push ${usage_tag:-"$GIT_SHA_SHORT-$GIT_DIFF_HASH"}',
]
