# coding: utf-8

# flake8: noqa

"""
Hevy API Docs

       Welcome to Hevy's public API! We're just starting to roll this out and depending on your       feedback, we'll be adding more features and endpoints. Also, we make no guarantees that        we won't completely change the structure or abandon the project entirely so use it at       your own risk. Currently, this API is only available to Hevy Pro users. You can get your        key on our web app at https://hevy.com/settings?developer. If you have any questions,       please reach out to pedro@hevyapp.com 🤝.

The version of the OpenAPI document: 0.0.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

__version__ = "1.0.0"

# Define package exports
__all__ = [
    "ExerciseHistoryApi",
    "ExerciseTemplatesApi",
    "RoutineFoldersApi",
    "RoutinesApi",
    "UsersApi",
    "WorkoutsApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "CreateCustomExerciseRequestBody",
    "CreateCustomExerciseRequestBodyExercise",
    "CreateCustomExerciseTemplate200Response",
    "CreateCustomExerciseTemplate400Response",
    "CreateCustomExerciseTemplate403Response",
    "CreateWorkout400Response",
    "CustomExerciseType",
    "DeletedWorkout",
    "EquipmentCategory",
    "Exercise",
    "ExerciseHistoryEntry",
    "ExerciseTemplate",
    "GetExerciseHistory200Response",
    "GetExerciseTemplates200Response",
    "GetRoutineById200Response",
    "GetRoutineFolders200Response",
    "GetRoutines200Response",
    "GetWorkoutCount200Response",
    "GetWorkouts200Response",
    "MuscleGroup",
    "PaginatedWorkoutEvents",
    "PaginatedWorkoutEventsEventsInner",
    "PostRoutineFolderRequestBody",
    "PostRoutineFolderRequestBodyRoutineFolder",
    "PostRoutinesRequestBody",
    "PostRoutinesRequestBodyRoutine",
    "PostRoutinesRequestExercise",
    "PostRoutinesRequestSet",
    "PostRoutinesRequestSetRepRange",
    "PostWorkoutsRequestBody",
    "PostWorkoutsRequestBodyWorkout",
    "PostWorkoutsRequestExercise",
    "PostWorkoutsRequestSet",
    "PutRoutinesRequestBody",
    "PutRoutinesRequestBodyRoutine",
    "PutRoutinesRequestExercise",
    "PutRoutinesRequestSet",
    "PutRoutinesRequestSetRepRange",
    "Routine",
    "RoutineExercisesInner",
    "RoutineExercisesInnerSetsInner",
    "RoutineFolder",
    "Set",
    "UpdatedWorkout",
    "UserInfo",
    "UserInfoResponse",
    "Workout",
    "WorkoutExercisesInner",
    "WorkoutExercisesInnerSetsInner",
]

# import apis into sdk package
from hevy_api_service.api.exercise_history_api import (
    ExerciseHistoryApi as ExerciseHistoryApi,
)
from hevy_api_service.api.exercise_templates_api import (
    ExerciseTemplatesApi as ExerciseTemplatesApi,
)
from hevy_api_service.api.routine_folders_api import (
    RoutineFoldersApi as RoutineFoldersApi,
)
from hevy_api_service.api.routines_api import RoutinesApi as RoutinesApi
from hevy_api_service.api.users_api import UsersApi as UsersApi
from hevy_api_service.api.workouts_api import WorkoutsApi as WorkoutsApi

# import ApiClient
from hevy_api_service.api_response import ApiResponse as ApiResponse
from hevy_api_service.api_client import ApiClient as ApiClient
from hevy_api_service.configuration import Configuration as Configuration
from hevy_api_service.exceptions import OpenApiException as OpenApiException
from hevy_api_service.exceptions import ApiTypeError as ApiTypeError
from hevy_api_service.exceptions import ApiValueError as ApiValueError
from hevy_api_service.exceptions import ApiKeyError as ApiKeyError
from hevy_api_service.exceptions import ApiAttributeError as ApiAttributeError
from hevy_api_service.exceptions import ApiException as ApiException

# import models into sdk package
from hevy_api_service.models.create_custom_exercise_request_body import (
    CreateCustomExerciseRequestBody as CreateCustomExerciseRequestBody,
)
from hevy_api_service.models.create_custom_exercise_request_body_exercise import (
    CreateCustomExerciseRequestBodyExercise as CreateCustomExerciseRequestBodyExercise,
)
from hevy_api_service.models.create_custom_exercise_template200_response import (
    CreateCustomExerciseTemplate200Response as CreateCustomExerciseTemplate200Response,
)
from hevy_api_service.models.create_custom_exercise_template400_response import (
    CreateCustomExerciseTemplate400Response as CreateCustomExerciseTemplate400Response,
)
from hevy_api_service.models.create_custom_exercise_template403_response import (
    CreateCustomExerciseTemplate403Response as CreateCustomExerciseTemplate403Response,
)
from hevy_api_service.models.create_workout400_response import (
    CreateWorkout400Response as CreateWorkout400Response,
)
from hevy_api_service.models.custom_exercise_type import (
    CustomExerciseType as CustomExerciseType,
)
from hevy_api_service.models.deleted_workout import DeletedWorkout as DeletedWorkout
from hevy_api_service.models.equipment_category import (
    EquipmentCategory as EquipmentCategory,
)
from hevy_api_service.models.exercise import Exercise as Exercise
from hevy_api_service.models.exercise_history_entry import (
    ExerciseHistoryEntry as ExerciseHistoryEntry,
)
from hevy_api_service.models.exercise_template import (
    ExerciseTemplate as ExerciseTemplate,
)
from hevy_api_service.models.get_exercise_history200_response import (
    GetExerciseHistory200Response as GetExerciseHistory200Response,
)
from hevy_api_service.models.get_exercise_templates200_response import (
    GetExerciseTemplates200Response as GetExerciseTemplates200Response,
)
from hevy_api_service.models.get_routine_by_id200_response import (
    GetRoutineById200Response as GetRoutineById200Response,
)
from hevy_api_service.models.get_routine_folders200_response import (
    GetRoutineFolders200Response as GetRoutineFolders200Response,
)
from hevy_api_service.models.get_routines200_response import (
    GetRoutines200Response as GetRoutines200Response,
)
from hevy_api_service.models.get_workout_count200_response import (
    GetWorkoutCount200Response as GetWorkoutCount200Response,
)
from hevy_api_service.models.get_workouts200_response import (
    GetWorkouts200Response as GetWorkouts200Response,
)
from hevy_api_service.models.muscle_group import MuscleGroup as MuscleGroup
from hevy_api_service.models.paginated_workout_events import (
    PaginatedWorkoutEvents as PaginatedWorkoutEvents,
)
from hevy_api_service.models.paginated_workout_events_events_inner import (
    PaginatedWorkoutEventsEventsInner as PaginatedWorkoutEventsEventsInner,
)
from hevy_api_service.models.post_routine_folder_request_body import (
    PostRoutineFolderRequestBody as PostRoutineFolderRequestBody,
)
from hevy_api_service.models.post_routine_folder_request_body_routine_folder import (
    PostRoutineFolderRequestBodyRoutineFolder as PostRoutineFolderRequestBodyRoutineFolder,
)
from hevy_api_service.models.post_routines_request_body import (
    PostRoutinesRequestBody as PostRoutinesRequestBody,
)
from hevy_api_service.models.post_routines_request_body_routine import (
    PostRoutinesRequestBodyRoutine as PostRoutinesRequestBodyRoutine,
)
from hevy_api_service.models.post_routines_request_exercise import (
    PostRoutinesRequestExercise as PostRoutinesRequestExercise,
)
from hevy_api_service.models.post_routines_request_set import (
    PostRoutinesRequestSet as PostRoutinesRequestSet,
)
from hevy_api_service.models.post_routines_request_set_rep_range import (
    PostRoutinesRequestSetRepRange as PostRoutinesRequestSetRepRange,
)
from hevy_api_service.models.post_workouts_request_body import (
    PostWorkoutsRequestBody as PostWorkoutsRequestBody,
)
from hevy_api_service.models.post_workouts_request_body_workout import (
    PostWorkoutsRequestBodyWorkout as PostWorkoutsRequestBodyWorkout,
)
from hevy_api_service.models.post_workouts_request_exercise import (
    PostWorkoutsRequestExercise as PostWorkoutsRequestExercise,
)
from hevy_api_service.models.post_workouts_request_set import (
    PostWorkoutsRequestSet as PostWorkoutsRequestSet,
)
from hevy_api_service.models.put_routines_request_body import (
    PutRoutinesRequestBody as PutRoutinesRequestBody,
)
from hevy_api_service.models.put_routines_request_body_routine import (
    PutRoutinesRequestBodyRoutine as PutRoutinesRequestBodyRoutine,
)
from hevy_api_service.models.put_routines_request_exercise import (
    PutRoutinesRequestExercise as PutRoutinesRequestExercise,
)
from hevy_api_service.models.put_routines_request_set import (
    PutRoutinesRequestSet as PutRoutinesRequestSet,
)
from hevy_api_service.models.put_routines_request_set_rep_range import (
    PutRoutinesRequestSetRepRange as PutRoutinesRequestSetRepRange,
)
from hevy_api_service.models.routine import Routine as Routine
from hevy_api_service.models.routine_exercises_inner import (
    RoutineExercisesInner as RoutineExercisesInner,
)
from hevy_api_service.models.routine_exercises_inner_sets_inner import (
    RoutineExercisesInnerSetsInner as RoutineExercisesInnerSetsInner,
)
from hevy_api_service.models.routine_folder import RoutineFolder as RoutineFolder
from hevy_api_service.models.set import Set as Set
from hevy_api_service.models.updated_workout import UpdatedWorkout as UpdatedWorkout
from hevy_api_service.models.user_info import UserInfo as UserInfo
from hevy_api_service.models.user_info_response import (
    UserInfoResponse as UserInfoResponse,
)
from hevy_api_service.models.workout import Workout as Workout
from hevy_api_service.models.workout_exercises_inner import (
    WorkoutExercisesInner as WorkoutExercisesInner,
)
from hevy_api_service.models.workout_exercises_inner_sets_inner import (
    WorkoutExercisesInnerSetsInner as WorkoutExercisesInnerSetsInner,
)
