"""
RP Strength Training API

RP Strength Training API for workout data, user profiles, subscriptions, and training management.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from api_service_rp.api.auth_api import AuthApi


class TestAuthApi(unittest.TestCase):
    """AuthApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthApi()

    def tearDown(self) -> None:
        pass

    def test_create_user(self) -> None:
        """Test case for create_user

        Create/update user
        """
        pass

    def test_login(self) -> None:
        """Test case for login

        Login
        """
        pass

    def test_magic_link_login(self) -> None:
        """Test case for magic_link_login

        Magic link login
        """
        pass


if __name__ == "__main__":
    unittest.main()
