kestra:
  tutorial-flows:
    enabled: false
  ai:
    type: gemini
    gemini:
      model-name: "gemini-3-flash-preview"
micronaut:
  io:
    watch:
      enabled: true
      paths:
        - /app/flows
