"""
Hevy API Docs

       Welcome to Hevy's public API! We're just starting to roll this out and depending on your       feedback, we'll be adding more features and endpoints. Also, we make no guarantees that        we won't completely change the structure or abandon the project entirely so use it at       your own risk. Currently, this API is only available to Hevy Pro users. You can get your        key on our web app at https://hevy.com/settings?developer. If you have any questions,       please reach out to pedro@hevyapp.com 🤝.

The version of the OpenAPI document: 0.0.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import re  # noqa: F401
from typing import Annotated

from pydantic import Field, StrictInt, StrictStr, validate_arguments

from hevy_api_service.api_client import ApiClient
from hevy_api_service.api_response import ApiResponse
from hevy_api_service.exceptions import ApiTypeError, ApiValueError  # noqa: F401
from hevy_api_service.models.get_routine_folders200_response import (
    GetRoutineFolders200Response,
)
from hevy_api_service.models.post_routine_folder_request_body import (
    PostRoutineFolderRequestBody,
)
from hevy_api_service.models.routine_folder import RoutineFolder


class RoutineFoldersApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client

    @validate_arguments
    def create_routine_folder(
        self,
        api_key: StrictStr,
        post_routine_folder_request_body: PostRoutineFolderRequestBody,
        **kwargs,
    ) -> RoutineFolder:  # noqa: E501
        """Create a new routine folder. The folder will be created at index 0, and all other folders will have their indexes incremented.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.create_routine_folder(api_key, post_routine_folder_request_body, async_req=True)
        >>> result = thread.get()

        :param api_key: (required)
        :type api_key: str
        :param post_routine_folder_request_body: (required)
        :type post_routine_folder_request_body: PostRoutineFolderRequestBody
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: RoutineFolder
        """
        kwargs["_return_http_data_only"] = True
        if "_preload_content" in kwargs:
            message = "Error! Please call the create_routine_folder_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.create_routine_folder_with_http_info(
            api_key, post_routine_folder_request_body, **kwargs
        )  # noqa: E501

    @validate_arguments
    def create_routine_folder_with_http_info(
        self,
        api_key: StrictStr,
        post_routine_folder_request_body: PostRoutineFolderRequestBody,
        **kwargs,
    ) -> ApiResponse:  # noqa: E501
        """Create a new routine folder. The folder will be created at index 0, and all other folders will have their indexes incremented.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.create_routine_folder_with_http_info(api_key, post_routine_folder_request_body, async_req=True)
        >>> result = thread.get()

        :param api_key: (required)
        :type api_key: str
        :param post_routine_folder_request_body: (required)
        :type post_routine_folder_request_body: PostRoutineFolderRequestBody
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(RoutineFolder, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = ["api_key", "post_routine_folder_request_body"]
        _all_params.extend(
            [
                "async_req",
                "_return_http_data_only",
                "_preload_content",
                "_request_timeout",
                "_request_auth",
                "_content_type",
                "_headers",
            ]
        )

        # validate the arguments
        for _key, _val in _params["kwargs"].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method create_routine_folder" % _key
                )
            _params[_key] = _val
        del _params["kwargs"]

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get("_headers", {}))
        if _params["api_key"] is not None:
            _header_params["api-key"] = _params["api_key"]

        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        if _params["post_routine_folder_request_body"] is not None:
            _body_params = _params["post_routine_folder_request_body"]

        # set the HTTP header `Accept`
        _header_params["Accept"] = self.api_client.select_header_accept(
            ["application/json"]
        )  # noqa: E501

        # set the HTTP header `Content-Type`
        _content_types_list = _params.get(
            "_content_type",
            self.api_client.select_header_content_type(["application/json"]),
        )
        if _content_types_list:
            _header_params["Content-Type"] = _content_types_list

        # authentication setting
        _auth_settings = []  # noqa: E501

        _response_types_map = {
            "201": "RoutineFolder",
            "400": "CreateWorkout400Response",
        }

        return self.api_client.call_api(
            "/v1/routine_folders",
            "POST",
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get("async_req"),
            _return_http_data_only=_params.get("_return_http_data_only"),  # noqa: E501
            _preload_content=_params.get("_preload_content", True),
            _request_timeout=_params.get("_request_timeout"),
            collection_formats=_collection_formats,
            _request_auth=_params.get("_request_auth"),
        )

    @validate_arguments
    def get_routine_folder_by_id(
        self,
        api_key: StrictStr,
        folder_id: Annotated[
            StrictStr, Field(..., description="The id of the routine folder")
        ],
        **kwargs,
    ) -> RoutineFolder:  # noqa: E501
        """Get a single routine folder by id.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_routine_folder_by_id(api_key, folder_id, async_req=True)
        >>> result = thread.get()

        :param api_key: (required)
        :type api_key: str
        :param folder_id: The id of the routine folder (required)
        :type folder_id: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: RoutineFolder
        """
        kwargs["_return_http_data_only"] = True
        if "_preload_content" in kwargs:
            message = "Error! Please call the get_routine_folder_by_id_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.get_routine_folder_by_id_with_http_info(
            api_key, folder_id, **kwargs
        )  # noqa: E501

    @validate_arguments
    def get_routine_folder_by_id_with_http_info(
        self,
        api_key: StrictStr,
        folder_id: Annotated[
            StrictStr, Field(..., description="The id of the routine folder")
        ],
        **kwargs,
    ) -> ApiResponse:  # noqa: E501
        """Get a single routine folder by id.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_routine_folder_by_id_with_http_info(api_key, folder_id, async_req=True)
        >>> result = thread.get()

        :param api_key: (required)
        :type api_key: str
        :param folder_id: The id of the routine folder (required)
        :type folder_id: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(RoutineFolder, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = ["api_key", "folder_id"]
        _all_params.extend(
            [
                "async_req",
                "_return_http_data_only",
                "_preload_content",
                "_request_timeout",
                "_request_auth",
                "_content_type",
                "_headers",
            ]
        )

        # validate the arguments
        for _key, _val in _params["kwargs"].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_routine_folder_by_id" % _key
                )
            _params[_key] = _val
        del _params["kwargs"]

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params["folder_id"] is not None:
            _path_params["folderId"] = _params["folder_id"]

        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get("_headers", {}))
        if _params["api_key"] is not None:
            _header_params["api-key"] = _params["api_key"]

        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params["Accept"] = self.api_client.select_header_accept(
            ["application/json"]
        )  # noqa: E501

        # authentication setting
        _auth_settings = []  # noqa: E501

        _response_types_map = {
            "200": "RoutineFolder",
            "404": None,
        }

        return self.api_client.call_api(
            "/v1/routine_folders/{folderId}",
            "GET",
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get("async_req"),
            _return_http_data_only=_params.get("_return_http_data_only"),  # noqa: E501
            _preload_content=_params.get("_preload_content", True),
            _request_timeout=_params.get("_request_timeout"),
            collection_formats=_collection_formats,
            _request_auth=_params.get("_request_auth"),
        )

    @validate_arguments
    def get_routine_folders(
        self,
        api_key: StrictStr,
        page: Annotated[
            StrictInt | None, Field(description="Page number (Must be 1 or greater)")
        ] = None,
        page_size: Annotated[
            StrictInt | None,
            Field(description="Number of items on the requested page (Max 10)"),
        ] = None,
        **kwargs,
    ) -> GetRoutineFolders200Response:  # noqa: E501
        """Get a paginated list of routine folders available on the account.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_routine_folders(api_key, page, page_size, async_req=True)
        >>> result = thread.get()

        :param api_key: (required)
        :type api_key: str
        :param page: Page number (Must be 1 or greater)
        :type page: int
        :param page_size: Number of items on the requested page (Max 10)
        :type page_size: int
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: GetRoutineFolders200Response
        """
        kwargs["_return_http_data_only"] = True
        if "_preload_content" in kwargs:
            message = "Error! Please call the get_routine_folders_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.get_routine_folders_with_http_info(
            api_key, page, page_size, **kwargs
        )  # noqa: E501

    @validate_arguments
    def get_routine_folders_with_http_info(
        self,
        api_key: StrictStr,
        page: Annotated[
            StrictInt | None, Field(description="Page number (Must be 1 or greater)")
        ] = None,
        page_size: Annotated[
            StrictInt | None,
            Field(description="Number of items on the requested page (Max 10)"),
        ] = None,
        **kwargs,
    ) -> ApiResponse:  # noqa: E501
        """Get a paginated list of routine folders available on the account.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_routine_folders_with_http_info(api_key, page, page_size, async_req=True)
        >>> result = thread.get()

        :param api_key: (required)
        :type api_key: str
        :param page: Page number (Must be 1 or greater)
        :type page: int
        :param page_size: Number of items on the requested page (Max 10)
        :type page_size: int
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(GetRoutineFolders200Response, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = ["api_key", "page", "page_size"]
        _all_params.extend(
            [
                "async_req",
                "_return_http_data_only",
                "_preload_content",
                "_request_timeout",
                "_request_auth",
                "_content_type",
                "_headers",
            ]
        )

        # validate the arguments
        for _key, _val in _params["kwargs"].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_routine_folders" % _key
                )
            _params[_key] = _val
        del _params["kwargs"]

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        if _params.get("page") is not None:  # noqa: E501
            _query_params.append(("page", _params["page"]))

        if _params.get("page_size") is not None:  # noqa: E501
            _query_params.append(("pageSize", _params["page_size"]))

        # process the header parameters
        _header_params = dict(_params.get("_headers", {}))
        if _params["api_key"] is not None:
            _header_params["api-key"] = _params["api_key"]

        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params["Accept"] = self.api_client.select_header_accept(
            ["application/json"]
        )  # noqa: E501

        # authentication setting
        _auth_settings = []  # noqa: E501

        _response_types_map = {
            "200": "GetRoutineFolders200Response",
            "400": None,
        }

        return self.api_client.call_api(
            "/v1/routine_folders",
            "GET",
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get("async_req"),
            _return_http_data_only=_params.get("_return_http_data_only"),  # noqa: E501
            _preload_content=_params.get("_preload_content", True),
            _request_timeout=_params.get("_request_timeout"),
            collection_formats=_collection_formats,
            _request_auth=_params.get("_request_auth"),
        )
