"""
Hevy API Docs

       Welcome to Hevy's public API! We're just starting to roll this out and depending on your       feedback, we'll be adding more features and endpoints. Also, we make no guarantees that        we won't completely change the structure or abandon the project entirely so use it at       your own risk. Currently, this API is only available to Hevy Pro users. You can get your        key on our web app at https://hevy.com/settings?developer. If you have any questions,       please reach out to pedro@hevyapp.com 🤝.

The version of the OpenAPI document: 0.0.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401

from pydantic import BaseModel, Field, StrictStr, conlist

from hevy_api_service.models.custom_exercise_type import CustomExerciseType
from hevy_api_service.models.equipment_category import EquipmentCategory
from hevy_api_service.models.muscle_group import MuscleGroup


class CreateCustomExerciseRequestBodyExercise(BaseModel):
    """
    CreateCustomExerciseRequestBodyExercise
    """

    title: StrictStr | None = Field(
        default=None, description="The title of the exercise template."
    )
    exercise_type: CustomExerciseType | None = None
    equipment_category: EquipmentCategory | None = None
    muscle_group: MuscleGroup | None = None
    other_muscles: conlist(MuscleGroup) | None = Field(
        default=None, description="The other muscles of the exercise template."
    )
    __properties = [
        "title",
        "exercise_type",
        "equipment_category",
        "muscle_group",
        "other_muscles",
    ]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> CreateCustomExerciseRequestBodyExercise:
        """Create an instance of CreateCustomExerciseRequestBodyExercise from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> CreateCustomExerciseRequestBodyExercise:
        """Create an instance of CreateCustomExerciseRequestBodyExercise from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return CreateCustomExerciseRequestBodyExercise.parse_obj(obj)

        _obj = CreateCustomExerciseRequestBodyExercise.parse_obj(
            {
                "title": obj.get("title"),
                "exercise_type": obj.get("exercise_type"),
                "equipment_category": obj.get("equipment_category"),
                "muscle_group": obj.get("muscle_group"),
                "other_muscles": obj.get("other_muscles"),
            }
        )
        return _obj
