"""
Hevy API Docs

       Welcome to Hevy's public API! We're just starting to roll this out and depending on your       feedback, we'll be adding more features and endpoints. Also, we make no guarantees that        we won't completely change the structure or abandon the project entirely so use it at       your own risk. Currently, this API is only available to Hevy Pro users. You can get your        key on our web app at https://hevy.com/settings?developer. If you have any questions,       please reach out to pedro@hevyapp.com 🤝.

The version of the OpenAPI document: 0.0.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401

from pydantic import BaseModel, Field, StrictBool, StrictStr, conlist


class ExerciseTemplate(BaseModel):
    """
    ExerciseTemplate
    """

    id: StrictStr | None = Field(default=None, description="The exercise template ID.")
    title: StrictStr | None = Field(default=None, description="The exercise title.")
    type: StrictStr | None = Field(default=None, description="The exercise type.")
    primary_muscle_group: StrictStr | None = Field(
        default=None, description="The primary muscle group of the exercise."
    )
    secondary_muscle_groups: conlist(StrictStr) | None = Field(
        default=None, description="The secondary muscle groups of the exercise."
    )
    is_custom: StrictBool | None = Field(
        default=None,
        description="A boolean indicating whether the exercise is a custom exercise.",
    )
    __properties = [
        "id",
        "title",
        "type",
        "primary_muscle_group",
        "secondary_muscle_groups",
        "is_custom",
    ]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ExerciseTemplate:
        """Create an instance of ExerciseTemplate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ExerciseTemplate:
        """Create an instance of ExerciseTemplate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ExerciseTemplate.parse_obj(obj)

        _obj = ExerciseTemplate.parse_obj(
            {
                "id": obj.get("id"),
                "title": obj.get("title"),
                "type": obj.get("type"),
                "primary_muscle_group": obj.get("primary_muscle_group"),
                "secondary_muscle_groups": obj.get("secondary_muscle_groups"),
                "is_custom": obj.get("is_custom"),
            }
        )
        return _obj
