"""
Hevy API Docs

       Welcome to Hevy's public API! We're just starting to roll this out and depending on your       feedback, we'll be adding more features and endpoints. Also, we make no guarantees that        we won't completely change the structure or abandon the project entirely so use it at       your own risk. Currently, this API is only available to Hevy Pro users. You can get your        key on our web app at https://hevy.com/settings?developer. If you have any questions,       please reach out to pedro@hevyapp.com 🤝.

The version of the OpenAPI document: 0.0.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401

from pydantic import BaseModel, Field, StrictInt, conlist

from hevy_api_service.models.exercise_template import ExerciseTemplate


class GetExerciseTemplates200Response(BaseModel):
    """
    GetExerciseTemplates200Response
    """

    page: StrictInt | None = Field(default=1, description="Current page number")
    page_count: StrictInt | None = Field(default=5, description="Total number of pages")
    exercise_templates: conlist(ExerciseTemplate) | None = None
    __properties = ["page", "page_count", "exercise_templates"]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> GetExerciseTemplates200Response:
        """Create an instance of GetExerciseTemplates200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in exercise_templates (list)
        _items = []
        if self.exercise_templates:
            for _item in self.exercise_templates:
                if _item:
                    _items.append(_item.to_dict())
            _dict["exercise_templates"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> GetExerciseTemplates200Response:
        """Create an instance of GetExerciseTemplates200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return GetExerciseTemplates200Response.parse_obj(obj)

        _obj = GetExerciseTemplates200Response.parse_obj(
            {
                "page": obj.get("page") if obj.get("page") is not None else 1,
                "page_count": obj.get("page_count")
                if obj.get("page_count") is not None
                else 5,
                "exercise_templates": [
                    ExerciseTemplate.from_dict(_item)
                    for _item in obj.get("exercise_templates")
                ]
                if obj.get("exercise_templates") is not None
                else None,
            }
        )
        return _obj
