"""
Hevy API Docs

       Welcome to Hevy's public API! We're just starting to roll this out and depending on your       feedback, we'll be adding more features and endpoints. Also, we make no guarantees that        we won't completely change the structure or abandon the project entirely so use it at       your own risk. Currently, this API is only available to Hevy Pro users. You can get your        key on our web app at https://hevy.com/settings?developer. If you have any questions,       please reach out to pedro@hevyapp.com 🤝.

The version of the OpenAPI document: 0.0.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401

from pydantic import BaseModel

from hevy_api_service.models.routine import Routine


class GetRoutineById200Response(BaseModel):
    """
    GetRoutineById200Response
    """

    routine: Routine | None = None
    __properties = ["routine"]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> GetRoutineById200Response:
        """Create an instance of GetRoutineById200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of routine
        if self.routine:
            _dict["routine"] = self.routine.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> GetRoutineById200Response:
        """Create an instance of GetRoutineById200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return GetRoutineById200Response.parse_obj(obj)

        _obj = GetRoutineById200Response.parse_obj(
            {
                "routine": Routine.from_dict(obj.get("routine"))
                if obj.get("routine") is not None
                else None
            }
        )
        return _obj
