"""
Hevy API Docs

       Welcome to Hevy's public API! We're just starting to roll this out and depending on your       feedback, we'll be adding more features and endpoints. Also, we make no guarantees that        we won't completely change the structure or abandon the project entirely so use it at       your own risk. Currently, this API is only available to Hevy Pro users. You can get your        key on our web app at https://hevy.com/settings?developer. If you have any questions,       please reach out to pedro@hevyapp.com 🤝.

The version of the OpenAPI document: 0.0.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401

from pydantic import BaseModel, Field, StrictInt, StrictStr, conlist

from hevy_api_service.models.post_routines_request_set import PostRoutinesRequestSet


class PostRoutinesRequestExercise(BaseModel):
    """
    PostRoutinesRequestExercise
    """

    exercise_template_id: StrictStr | None = Field(
        default=None, description="The ID of the exercise template."
    )
    superset_id: StrictInt | None = Field(
        default=None, description="The ID of the superset."
    )
    rest_seconds: StrictInt | None = Field(
        default=None, description="The rest time in seconds."
    )
    notes: StrictStr | None = Field(
        default=None, description="Additional notes for the exercise."
    )
    sets: conlist(PostRoutinesRequestSet) | None = None
    __properties = [
        "exercise_template_id",
        "superset_id",
        "rest_seconds",
        "notes",
        "sets",
    ]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> PostRoutinesRequestExercise:
        """Create an instance of PostRoutinesRequestExercise from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in sets (list)
        _items = []
        if self.sets:
            for _item in self.sets:
                if _item:
                    _items.append(_item.to_dict())
            _dict["sets"] = _items
        # set to None if superset_id (nullable) is None
        # and __fields_set__ contains the field
        if self.superset_id is None and "superset_id" in self.__fields_set__:
            _dict["superset_id"] = None

        # set to None if rest_seconds (nullable) is None
        # and __fields_set__ contains the field
        if self.rest_seconds is None and "rest_seconds" in self.__fields_set__:
            _dict["rest_seconds"] = None

        # set to None if notes (nullable) is None
        # and __fields_set__ contains the field
        if self.notes is None and "notes" in self.__fields_set__:
            _dict["notes"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> PostRoutinesRequestExercise:
        """Create an instance of PostRoutinesRequestExercise from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return PostRoutinesRequestExercise.parse_obj(obj)

        _obj = PostRoutinesRequestExercise.parse_obj(
            {
                "exercise_template_id": obj.get("exercise_template_id"),
                "superset_id": obj.get("superset_id"),
                "rest_seconds": obj.get("rest_seconds"),
                "notes": obj.get("notes"),
                "sets": [
                    PostRoutinesRequestSet.from_dict(_item) for _item in obj.get("sets")
                ]
                if obj.get("sets") is not None
                else None,
            }
        )
        return _obj
