"""
Hevy API Docs

       Welcome to Hevy's public API! We're just starting to roll this out and depending on your       feedback, we'll be adding more features and endpoints. Also, we make no guarantees that        we won't completely change the structure or abandon the project entirely so use it at       your own risk. Currently, this API is only available to Hevy Pro users. You can get your        key on our web app at https://hevy.com/settings?developer. If you have any questions,       please reach out to pedro@hevyapp.com 🤝.

The version of the OpenAPI document: 0.0.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401

from pydantic import BaseModel, Field, StrictFloat, StrictInt, StrictStr, conlist

from hevy_api_service.models.post_routines_request_exercise import (
    PostRoutinesRequestExercise,
)


class PostRoutinesRequestBodyRoutine(BaseModel):
    """
    PostRoutinesRequestBodyRoutine
    """

    title: StrictStr | None = Field(
        default=None, description="The title of the routine."
    )
    folder_id: StrictFloat | StrictInt | None = Field(
        default=None,
        description='The folder id the routine should be added to. Pass null to insert the routine into default "My Routines" folder',
    )
    notes: StrictStr | None = Field(
        default=None, description="Additional notes for the routine."
    )
    exercises: conlist(PostRoutinesRequestExercise) | None = None
    __properties = ["title", "folder_id", "notes", "exercises"]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> PostRoutinesRequestBodyRoutine:
        """Create an instance of PostRoutinesRequestBodyRoutine from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in exercises (list)
        _items = []
        if self.exercises:
            for _item in self.exercises:
                if _item:
                    _items.append(_item.to_dict())
            _dict["exercises"] = _items
        # set to None if folder_id (nullable) is None
        # and __fields_set__ contains the field
        if self.folder_id is None and "folder_id" in self.__fields_set__:
            _dict["folder_id"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> PostRoutinesRequestBodyRoutine:
        """Create an instance of PostRoutinesRequestBodyRoutine from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return PostRoutinesRequestBodyRoutine.parse_obj(obj)

        _obj = PostRoutinesRequestBodyRoutine.parse_obj(
            {
                "title": obj.get("title"),
                "folder_id": obj.get("folder_id"),
                "notes": obj.get("notes"),
                "exercises": [
                    PostRoutinesRequestExercise.from_dict(_item)
                    for _item in obj.get("exercises")
                ]
                if obj.get("exercises") is not None
                else None,
            }
        )
        return _obj
