"""
Hevy API Docs

       Welcome to Hevy's public API! We're just starting to roll this out and depending on your       feedback, we'll be adding more features and endpoints. Also, we make no guarantees that        we won't completely change the structure or abandon the project entirely so use it at       your own risk. Currently, this API is only available to Hevy Pro users. You can get your        key on our web app at https://hevy.com/settings?developer. If you have any questions,       please reach out to pedro@hevyapp.com 🤝.

The version of the OpenAPI document: 0.0.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401

from pydantic import BaseModel, Field, StrictStr, conlist

from hevy_api_service.models.put_routines_request_exercise import (
    PutRoutinesRequestExercise,
)


class PutRoutinesRequestBodyRoutine(BaseModel):
    """
    PutRoutinesRequestBodyRoutine
    """

    title: StrictStr | None = Field(
        default=None, description="The title of the routine."
    )
    notes: StrictStr | None = Field(
        default=None, description="Additional notes for the routine."
    )
    exercises: conlist(PutRoutinesRequestExercise) | None = None
    __properties = ["title", "notes", "exercises"]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> PutRoutinesRequestBodyRoutine:
        """Create an instance of PutRoutinesRequestBodyRoutine from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in exercises (list)
        _items = []
        if self.exercises:
            for _item in self.exercises:
                if _item:
                    _items.append(_item.to_dict())
            _dict["exercises"] = _items
        # set to None if notes (nullable) is None
        # and __fields_set__ contains the field
        if self.notes is None and "notes" in self.__fields_set__:
            _dict["notes"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> PutRoutinesRequestBodyRoutine:
        """Create an instance of PutRoutinesRequestBodyRoutine from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return PutRoutinesRequestBodyRoutine.parse_obj(obj)

        _obj = PutRoutinesRequestBodyRoutine.parse_obj(
            {
                "title": obj.get("title"),
                "notes": obj.get("notes"),
                "exercises": [
                    PutRoutinesRequestExercise.from_dict(_item)
                    for _item in obj.get("exercises")
                ]
                if obj.get("exercises") is not None
                else None,
            }
        )
        return _obj
