"""
Hevy API Docs

       Welcome to Hevy's public API! We're just starting to roll this out and depending on your       feedback, we'll be adding more features and endpoints. Also, we make no guarantees that        we won't completely change the structure or abandon the project entirely so use it at       your own risk. Currently, this API is only available to Hevy Pro users. You can get your        key on our web app at https://hevy.com/settings?developer. If you have any questions,       please reach out to pedro@hevyapp.com 🤝.

The version of the OpenAPI document: 0.0.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401

from pydantic import BaseModel, Field, StrictFloat, StrictInt


class PutRoutinesRequestSetRepRange(BaseModel):
    """
    Range of reps for the set, if applicable  # noqa: E501
    """

    start: StrictFloat | StrictInt | None = Field(
        default=None, description="Starting rep count for the range"
    )
    end: StrictFloat | StrictInt | None = Field(
        default=None, description="Ending rep count for the range"
    )
    __properties = ["start", "end"]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> PutRoutinesRequestSetRepRange:
        """Create an instance of PutRoutinesRequestSetRepRange from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        # set to None if start (nullable) is None
        # and __fields_set__ contains the field
        if self.start is None and "start" in self.__fields_set__:
            _dict["start"] = None

        # set to None if end (nullable) is None
        # and __fields_set__ contains the field
        if self.end is None and "end" in self.__fields_set__:
            _dict["end"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> PutRoutinesRequestSetRepRange:
        """Create an instance of PutRoutinesRequestSetRepRange from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return PutRoutinesRequestSetRepRange.parse_obj(obj)

        _obj = PutRoutinesRequestSetRepRange.parse_obj(
            {"start": obj.get("start"), "end": obj.get("end")}
        )
        return _obj
