# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-02-28T19:33:14+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field


class Type(Enum):
    warmup = "warmup"
    normal = "normal"
    failure = "failure"
    dropset = "dropset"


class Rpe(Enum):
    number_6 = 6
    number_7 = 7
    number_7_5 = 7.5
    number_8 = 8
    number_8_5 = 8.5
    number_9 = 9
    number_9_5 = 9.5
    number_10 = 10


class PostWorkoutsRequestSet(BaseModel):
    type: Type | None = Field(
        None, description="The type of the set.", example="normal"
    )
    weight_kg: float | None = Field(
        None, description="The weight in kilograms.", example=100
    )
    reps: int | None = Field(None, description="The number of repetitions.", example=10)
    distance_meters: int | None = Field(None, description="The distance in meters.")
    duration_seconds: int | None = Field(None, description="The duration in seconds.")
    custom_metric: float | None = Field(
        None,
        description="A custom metric for the set. Currently used for steps and floors.",
    )
    rpe: Rpe | None = Field(None, description="The Rating of Perceived Exertion (RPE).")


class PostWorkoutsRequestExercise(BaseModel):
    exercise_template_id: str | None = Field(
        None, description="The ID of the exercise template.", example="D04AC939"
    )
    superset_id: int | None = Field(None, description="The ID of the superset.")
    notes: str | None = Field(
        None,
        description="Additional notes for the exercise.",
        example="Felt good today. Form was on point.",
    )
    sets: list[PostWorkoutsRequestSet] | None = None


class Workout(BaseModel):
    title: str | None = Field(
        None, description="The title of the workout.", example="Friday Leg Day 🔥"
    )
    description: str | None = Field(
        None,
        description="A description for the workout workout.",
        example="Medium intensity leg day focusing on quads.",
    )
    start_time: str | None = Field(
        None,
        description="The time the workout started.",
        example="2024-08-14T12:00:00Z",
    )
    end_time: str | None = Field(
        None, description="The time the workout ended.", example="2024-08-14T12:30:00Z"
    )
    is_private: bool | None = Field(
        None,
        description="A boolean indicating if the workout is private.",
        example=False,
    )
    exercises: list[PostWorkoutsRequestExercise] | None = None


class PostWorkoutsRequestBody(BaseModel):
    workout: Workout | None = None


class RepRange(BaseModel):
    start: float | None = Field(
        None, description="Starting rep count for the range", example=8
    )
    end: float | None = Field(
        None, description="Ending rep count for the range", example=12
    )


class PostRoutinesRequestSet(BaseModel):
    type: Type | None = Field(
        None, description="The type of the set.", example="normal"
    )
    weight_kg: float | None = Field(
        None, description="The weight in kilograms.", example=100
    )
    reps: int | None = Field(None, description="The number of repetitions.", example=10)
    distance_meters: int | None = Field(None, description="The distance in meters.")
    duration_seconds: int | None = Field(None, description="The duration in seconds.")
    custom_metric: float | None = Field(
        None,
        description="A custom metric for the set. Currently used for steps and floors.",
    )
    rep_range: RepRange | None = Field(
        None, description="Range of reps for the set, if applicable"
    )


class PostRoutinesRequestExercise(BaseModel):
    exercise_template_id: str | None = Field(
        None, description="The ID of the exercise template.", example="D04AC939"
    )
    superset_id: int | None = Field(None, description="The ID of the superset.")
    rest_seconds: int | None = Field(
        None, description="The rest time in seconds.", example=90
    )
    notes: str | None = Field(
        None,
        description="Additional notes for the exercise.",
        example="Stay slow and controlled.",
    )
    sets: list[PostRoutinesRequestSet] | None = None


class Routine(BaseModel):
    title: str | None = Field(
        None, description="The title of the routine.", example="April Leg Day 🔥"
    )
    folder_id: float | None = Field(
        None,
        description='The folder id the routine should be added to. Pass null to insert the routine into default "My Routines" folder',
    )
    notes: str | None = Field(
        None,
        description="Additional notes for the routine.",
        example="Focus on form over weight. Remember to stretch.",
    )
    exercises: list[PostRoutinesRequestExercise] | None = None


class PostRoutinesRequestBody(BaseModel):
    routine: Routine | None = None


class PutRoutinesRequestSet(BaseModel):
    type: Type | None = Field(
        None, description="The type of the set.", example="normal"
    )
    weight_kg: float | None = Field(
        None, description="The weight in kilograms.", example=100
    )
    reps: int | None = Field(None, description="The number of repetitions.", example=10)
    distance_meters: int | None = Field(None, description="The distance in meters.")
    duration_seconds: int | None = Field(None, description="The duration in seconds.")
    custom_metric: float | None = Field(
        None,
        description="A custom metric for the set. Currently used for steps and floors.",
    )
    rep_range: RepRange | None = Field(
        None, description="Range of reps for the set, if applicable"
    )


class PutRoutinesRequestExercise(BaseModel):
    exercise_template_id: str | None = Field(
        None, description="The ID of the exercise template.", example="D04AC939"
    )
    superset_id: int | None = Field(None, description="The ID of the superset.")
    rest_seconds: int | None = Field(
        None, description="The rest time in seconds.", example=90
    )
    notes: str | None = Field(
        None,
        description="Additional notes for the exercise.",
        example="Stay slow and controlled.",
    )
    sets: list[PutRoutinesRequestSet] | None = None


class Routine1(BaseModel):
    title: str | None = Field(
        None, description="The title of the routine.", example="April Leg Day 🔥"
    )
    notes: str | None = Field(
        None,
        description="Additional notes for the routine.",
        example="Focus on form over weight. Remember to stretch.",
    )
    exercises: list[PutRoutinesRequestExercise] | None = None


class PutRoutinesRequestBody(BaseModel):
    routine: Routine1 | None = None


class RoutineFolder(BaseModel):
    title: str | None = Field(
        None,
        description="The title of the routine folder.",
        example="Push Pull 🏋️\u200d♂️",
    )


class PostRoutineFolderRequestBody(BaseModel):
    routine_folder: RoutineFolder | None = None


class Set(BaseModel):
    index: float | None = Field(
        None,
        description="Index indicating the order of the set in the workout.",
        example=0,
    )
    type: str | None = Field(
        None,
        description="The type of set. This can be one of 'normal', 'warmup', 'dropset', 'failure'",
        example="normal",
    )
    weight_kg: float | None = Field(
        None, description="Weight lifted in kilograms.", example=100
    )
    reps: float | None = Field(
        None, description="Number of reps logged for the set", example=10
    )
    distance_meters: float | None = Field(
        None, description="Number of meters logged for the set"
    )
    duration_seconds: float | None = Field(
        None, description="Number of seconds logged for the set"
    )
    rpe: float | None = Field(
        None,
        description="RPE (Relative perceived exertion) value logged for the set",
        example=9.5,
    )
    custom_metric: float | None = Field(
        None,
        description="Custom metric logged for the set (Currently only used to log floors or steps for stair machine exercises)",
        example=50,
    )


class Exercise(BaseModel):
    index: float | None = Field(
        None,
        description="Index indicating the order of the exercise in the workout.",
        example=0,
    )
    title: str | None = Field(
        None, description="Title of the exercise", example="Bench Press (Barbell)"
    )
    notes: str | None = Field(
        None,
        description="Notes on the exercise",
        example="Paid closer attention to form today. Felt great!",
    )
    exercise_template_id: str | None = Field(
        None,
        description="The id of the exercise template. This can be used to fetch the exercise template.",
        example="05293BCA",
    )
    supersets_id: float | None = Field(
        None,
        description="The id of the superset that the exercise belongs to. A value of null indicates the exercise is not part of a superset.",
        example=0,
    )
    sets: list[Set] | None = None


class ExerciseHistoryEntry(BaseModel):
    workout_id: str | None = Field(
        None,
        description="The workout ID",
        example="b459cba5-cd6d-463c-abd6-54f8eafcadcb",
    )
    workout_title: str | None = Field(
        None, description="The workout title", example="Morning Workout 💪"
    )
    workout_start_time: str | None = Field(
        None,
        description="ISO 8601 timestamp of when the workout was recorded to have started.",
        example="2024-01-01T12:00:00Z",
    )
    workout_end_time: str | None = Field(
        None,
        description="ISO 8601 timestamp of when the workout was recorded to have ended.",
        example="2024-01-01T13:00:00Z",
    )
    exercise_template_id: str | None = Field(
        None, description="The exercise template ID", example="D04AC939"
    )
    weight_kg: float | None = Field(
        None, description="The weight in kilograms", example=100
    )
    reps: int | None = Field(None, description="The number of repetitions", example=10)
    distance_meters: int | None = Field(None, description="The distance in meters")
    duration_seconds: int | None = Field(None, description="The duration in seconds")
    rpe: float | None = Field(
        None, description="The Rating of Perceived Exertion", example=8.5
    )
    custom_metric: float | None = Field(None, description="A custom metric for the set")
    set_type: str | None = Field(
        None,
        description="The type of set (warmup, normal, failure, dropset)",
        example="normal",
    )


class CustomExerciseType(Enum):
    weight_reps = "weight_reps"
    reps_only = "reps_only"
    bodyweight_reps = "bodyweight_reps"
    bodyweight_assisted_reps = "bodyweight_assisted_reps"
    duration = "duration"
    weight_duration = "weight_duration"
    distance_duration = "distance_duration"
    short_distance_weight = "short_distance_weight"


class MuscleGroup(Enum):
    abdominals = "abdominals"
    shoulders = "shoulders"
    biceps = "biceps"
    triceps = "triceps"
    forearms = "forearms"
    quadriceps = "quadriceps"
    hamstrings = "hamstrings"
    calves = "calves"
    glutes = "glutes"
    abductors = "abductors"
    adductors = "adductors"
    lats = "lats"
    upper_back = "upper_back"
    traps = "traps"
    lower_back = "lower_back"
    chest = "chest"
    cardio = "cardio"
    neck = "neck"
    full_body = "full_body"
    other = "other"


class EquipmentCategory(Enum):
    none = "none"
    barbell = "barbell"
    dumbbell = "dumbbell"
    kettlebell = "kettlebell"
    machine = "machine"
    plate = "plate"
    resistance_band = "resistance_band"
    suspension = "suspension"
    other = "other"


class ExerciseTemplate(BaseModel):
    id: str | None = Field(
        None,
        description="The exercise template ID.",
        example="b459cba5-cd6d-463c-abd6-54f8eafcadcb",
    )
    title: str | None = Field(
        None, description="The exercise title.", example="Bench Press (Barbell)"
    )
    type: str | None = Field(
        None, description="The exercise type.", example="weight_reps"
    )
    primary_muscle_group: str | None = Field(
        None, description="The primary muscle group of the exercise.", example="chest"
    )
    secondary_muscle_groups: list[str] | None = Field(
        None, description="The secondary muscle groups of the exercise."
    )
    is_custom: bool | None = Field(
        None,
        description="A boolean indicating whether the exercise is a custom exercise.",
        example=False,
    )


class Exercise1(BaseModel):
    title: str | None = Field(
        None, description="The title of the exercise template.", example="Bench Press"
    )
    exercise_type: CustomExerciseType | None = None
    equipment_category: EquipmentCategory | None = Field(
        None,
        description="The equipment category of the exercise template.",
        example="barbell",
    )
    muscle_group: MuscleGroup | None = Field(
        None, description="The muscle group of the exercise template.", example="chest"
    )
    other_muscles: list[MuscleGroup] | None = Field(
        None,
        description="The other muscles of the exercise template.",
        example=["biceps", "triceps"],
    )


class CreateCustomExerciseRequestBody(BaseModel):
    exercise: Exercise1


class RoutineFolder1(BaseModel):
    id: float | None = Field(None, description="The routine folder ID.", example=42)
    index: float | None = Field(
        None,
        description="The routine folder index. Describes the order of the folder in the list.",
        example=1,
    )
    title: str | None = Field(
        None, description="The routine folder title.", example="Push Pull 🏋️\u200d♂️"
    )
    updated_at: str | None = Field(
        None,
        description="ISO 8601 timestamp of when the folder was last updated.",
        example="2021-09-14T12:00:00Z",
    )
    created_at: str | None = Field(
        None,
        description="ISO 8601 timestamp of when the folder was created.",
        example="2021-09-14T12:00:00Z",
    )


class Set1(BaseModel):
    index: float | None = Field(
        None,
        description="Index indicating the order of the set in the routine.",
        example=0,
    )
    type: str | None = Field(
        None,
        description="The type of set. This can be one of 'normal', 'warmup', 'dropset', 'failure'",
        example="normal",
    )
    weight_kg: float | None = Field(
        None, description="Weight lifted in kilograms.", example=100
    )
    reps: float | None = Field(
        None, description="Number of reps logged for the set", example=10
    )
    rep_range: RepRange | None = Field(
        None, description="Range of reps for the set, if applicable"
    )
    distance_meters: float | None = Field(
        None, description="Number of meters logged for the set"
    )
    duration_seconds: float | None = Field(
        None, description="Number of seconds logged for the set"
    )
    rpe: float | None = Field(
        None,
        description="RPE (Relative perceived exertion) value logged for the set",
        example=9.5,
    )
    custom_metric: float | None = Field(
        None,
        description="Custom metric logged for the set (Currently only used to log floors or steps for stair machine exercises)",
        example=50,
    )


class Exercise2(BaseModel):
    index: float | None = Field(
        None,
        description="Index indicating the order of the exercise in the routine.",
        example=0,
    )
    title: str | None = Field(
        None, description="Title of the exercise", example="Bench Press (Barbell)"
    )
    rest_seconds: str | None = Field(
        None,
        description="The rest time in seconds between sets of the exercise",
        example=60,
    )
    notes: str | None = Field(
        None,
        description="Routine notes on the exercise",
        example="Focus on form. Go down to 90 degrees.",
    )
    exercise_template_id: str | None = Field(
        None,
        description="The id of the exercise template. This can be used to fetch the exercise template.",
        example="05293BCA",
    )
    supersets_id: float | None = Field(
        None,
        description="The id of the superset that the exercise belongs to. A value of null indicates the exercise is not part of a superset.",
        example=0,
    )
    sets: list[Set1] | None = None


class Routine2(BaseModel):
    id: str | None = Field(
        None,
        description="The routine ID.",
        example="b459cba5-cd6d-463c-abd6-54f8eafcadcb",
    )
    title: str | None = Field(
        None, description="The routine title.", example="Upper Body 💪"
    )
    folder_id: float | None = Field(
        None, description="The routine folder ID.", example=42
    )
    updated_at: str | None = Field(
        None,
        description="ISO 8601 timestamp of when the routine was last updated.",
        example="2021-09-14T12:00:00Z",
    )
    created_at: str | None = Field(
        None,
        description="ISO 8601 timestamp of when the routine was created.",
        example="2021-09-14T12:00:00Z",
    )
    exercises: list[Exercise2] | None = None


class UserInfo(BaseModel):
    id: str | None = Field(
        None, description="The user ID.", example="9c465af3-de7d-42bc-9c7c-f0170396358b"
    )
    name: str | None = Field(
        None, description="The user's display name.", example="John doe"
    )
    url: str | None = Field(
        None,
        description="The user's public profile URL.",
        example="https://hevy.com/user/jhon",
    )


class UserInfoResponse(BaseModel):
    data: UserInfo | None = None


class Set2(BaseModel):
    index: float | None = Field(
        None,
        description="Index indicating the order of the set in the workout.",
        example=0,
    )
    type: str | None = Field(
        None,
        description="The type of set. This can be one of 'normal', 'warmup', 'dropset', 'failure'",
        example="normal",
    )
    weight_kg: float | None = Field(
        None, description="Weight lifted in kilograms.", example=100
    )
    reps: float | None = Field(
        None, description="Number of reps logged for the set", example=10
    )
    distance_meters: float | None = Field(
        None, description="Number of meters logged for the set"
    )
    duration_seconds: float | None = Field(
        None, description="Number of seconds logged for the set"
    )
    rpe: float | None = Field(
        None,
        description="RPE (Relative perceived exertion) value logged for the set",
        example=9.5,
    )
    custom_metric: float | None = Field(
        None,
        description="Custom metric logged for the set (Currently only used to log floors or steps for stair machine exercises)",
        example=50,
    )


class Exercise3(BaseModel):
    index: float | None = Field(
        None,
        description="Index indicating the order of the exercise in the workout.",
        example=0,
    )
    title: str | None = Field(
        None, description="Title of the exercise", example="Bench Press (Barbell)"
    )
    notes: str | None = Field(
        None,
        description="Notes on the exercise",
        example="Paid closer attention to form today. Felt great!",
    )
    exercise_template_id: str | None = Field(
        None,
        description="The id of the exercise template. This can be used to fetch the exercise template.",
        example="05293BCA",
    )
    supersets_id: float | None = Field(
        None,
        description="The id of the superset that the exercise belongs to. A value of null indicates the exercise is not part of a superset.",
        example=0,
    )
    sets: list[Set2] | None = None


class Workout1(BaseModel):
    id: str | None = Field(
        None,
        description="The workout ID.",
        example="b459cba5-cd6d-463c-abd6-54f8eafcadcb",
    )
    title: str | None = Field(
        None, description="The workout title.", example="Morning Workout 💪"
    )
    routine_id: str | None = Field(
        None,
        description="The ID of the routine that this workout belongs to.",
        example="b459cba5-cd6d-463c-abd6-54f8eafcadcb",
    )
    description: str | None = Field(
        None,
        description="The workout description.",
        example="Pushed myself to the limit today!",
    )
    start_time: str | None = Field(
        None,
        description="ISO 8601 timestamp of when the workout was recorded to have started.",
        example="2021-09-14T12:00:00Z",
    )
    end_time: str | None = Field(
        None,
        description="ISO 8601 timestamp of when the workout was recorded to have ended.",
        example="2021-09-14T12:00:00Z",
    )
    updated_at: str | None = Field(
        None,
        description="ISO 8601 timestamp of when the workout was last updated.",
        example="2021-09-14T12:00:00Z",
    )
    created_at: str | None = Field(
        None,
        description="ISO 8601 timestamp of when the workout was created.",
        example="2021-09-14T12:00:00Z",
    )
    exercises: list[Exercise3] | None = None


class UpdatedWorkout(BaseModel):
    type: str = Field(
        ..., description="Indicates the type of the event (updated)", example="updated"
    )
    workout: Workout1


class DeletedWorkout(BaseModel):
    type: str = Field(
        ..., description="Indicates the type of the event (deleted)", example="deleted"
    )
    id: str = Field(
        ...,
        description="The unique identifier of the deleted workout",
        example="efe6801c-4aee-4959-bcdd-fca3f272821b",
    )
    deleted_at: str | None = Field(
        None,
        description="A date string indicating when the workout was deleted",
        example="2021-09-13T12:00:00Z",
    )


class PaginatedWorkoutEvents(BaseModel):
    page: int = Field(..., description="The current page number", example=1)
    page_count: int = Field(
        ..., description="The total number of pages available", example=5
    )
    events: list[UpdatedWorkout | DeletedWorkout] = Field(
        ..., description="An array of workout events (either updated or deleted)"
    )
